language: objective-c

osx_image: xcode8

xcode_project: Apollo.xcodeproj
xcode_scheme: Apollo

xcode_sdk: iphonesimulator10.0

env:
  matrix:
    - DESTINATION="platform=iOS Simulator,OS=10.0,name=iPhone 7"
    - DESTINATION="platform=iOS Simulator,OS=9.3,name=iPhone 6s"

cache:
  directories:
    - ../starwars-server

before_install:
  - (./scripts/install-or-update-starwars-server.sh)
  - (cd ../starwars-server && npm start) &
  - npm install -g apollo-codegen

script:
  - set -o pipefail
  - xcodebuild clean build test -project "${TRAVIS_XCODE_PROJECT}" -scheme "${TRAVIS_XCODE_SCHEME}" -sdk "${TRAVIS_XCODE_SDK}" -destination "${DESTINATION}" | xcpretty
